function [ res ] = SVM_Gaus_class_fun( xTrain, yTrain, xTest)
%UNTITLED5 Summary of this function goes here
%   Detailed explanation goes here
op = statset('UseParallel',true);

template = templateSVM(...
    'KernelFunction', 'gaussian', ...
    'PolynomialOrder', [], ...
    'KernelScale', 0.7, ...
    'BoxConstraint', 1.7, ...
    'Standardize', true);
%    'alpha',alpha,...
classificationSVM = fitcecoc(...
    xTrain, ...
    yTrain, ...
    'Learners', template, ...
    'Coding', 'onevsone', ...
    'Options', op,...
    'ClassNames', [1; 2; 3; 4; 5; 6]);

res = predict(classificationSVM, xTest);
end

